title: "Leek Arop"
description: "Cybersecurity Researcher | CTF Player | Lecturer"

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Leek Arop"
  bio: "Cybersecurity Researcher | SOC | Forensics"
  location: "UK"
