title: "Leek Arop"
description: "Cybersecurity Researcher | CTF Player | Lecturer"

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Leek Arop"
  bio: "Cybersecurity Researcher | SOC | Forensics"
  location: "UK"
header:
  overlay_image: /assets/images/banner.gif
  overlay_filter: 0.6
  caption: "Cybersecurity | SOC | Digital Forensics"
