title: "Leek Arop"
description: "Cybersecurity Researcher | CTF Player | Lecturer"
theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "dark"

author:
  name: "Leek Arop"
  bio: "Cybersecurity Researcher | SOC | Forensics"
  location: "UK"
  email: "leekarop12@outlook.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
